# Generated by Django 5.0.6 on 2024-05-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='productsImg/')),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('rate', models.IntegerField()),
            ],
        ),
    ]
