# Generated by Django 5.0.6 on 2024-05-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0002_products_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='rate',
            field=models.IntegerField(verbose_name=range(1, 5)),
        ),
    ]
